### ISSUE TITLE
Give an example how to run this locally on a package

### ISSUE THREAD

**Issue by KristofferC** [bcbi/CompatHelper.jl#161] opened 2019-11-27 09:26 UTC
I just want to run this on a package I have locally on disk without any PRs or GitHub usage etc.

It seems right now, the code mixes the logic for updating the project file with the GitHub features. It would be nice if those two features could be kept separate.

**Comment by DilumAluthge** [comment] 2019-11-27 19:12
Duplicate of #85?

**Comment by DilumAluthge** [comment] 2019-11-27 19:13
I think it’s a good feature, and one that we need to add. I just haven’t had time to work on it.

**Comment by DilumAluthge** [comment] 2019-11-27 20:38
I’m going to close this as a duplicate of #85. @KristofferC let me know if I am mistaken.

**Closed by DilumAluthge** 2019-11-27 20:38 UTC
Labels: enhancement

**Comment by KristofferC** [comment] 2019-11-29 11:47
Sorry missed that! Indeed a duplicate.
