### ISSUE TITLE
What about:

### ISSUE THREAD

**Issue by devilhoova** [bcbi/CompatHelper.jl#192] opened 2020-04-16 11:59 UTC
What about:
1) Create a temp copy of the project.
2) Delete all `[compat]` entries except for `julia`
3) `Pkg.update()`
4) Read back the versions in the updated manifest.

That should get you the latest possible versions of all packages while respecting the upper bounds of dependencies, right?

_Originally posted by @colinxs in https://github.com/bcbi/CompatHelper.jl/issues/160#issuecomment-559328959_

**Comment by colinxs** [comment] 2020-04-16 17:34
I'm not sure why you opened a new issue but as discussed in #160 that only partly works. You'll get the correct compat entries but at test time you may get a different set of dependencies, preventing you from testing those new compat entries.

**Comment by DilumAluthge** [comment] 2020-04-16 19:20
Duplicate of #160. Let's keep the discussion in that thread.

**Closed by DilumAluthge** 2020-04-16 19:20 UTC
