### ISSUE TITLE
no method matching _repos_are_the_same(::GitHub.Repo, ::Nothing)

### ISSUE THREAD

**Issue by timholy** [bcbi/CompatHelper.jl#140] opened 2019-11-23 16:10 UTC
https://github.com/JuliaImages/Images.jl/runs/317468145

**Comment by DilumAluthge** [comment] 2019-11-23 23:21
Good find. I know the cause. Basically happens when someone made a pull request he repository from a fork, and then the pull request was merged and they deleted the fork.

This should be a pretty easy bag for me to fix.

**Closed** 2019-11-23 23:58 UTC
Labels: bug

**Comment by timholy** [comment] 2019-11-24 00:02
You're a god, @DilumAluthge!
